server:
  port: 8085

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: Edgar123456/
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

auth:
  jwtSecret: "mi_super_clave_secreta_para_jwt_2025_con_al_menos_64_caracteres_para_HS512_seguridad_completa"
  jwtExpirationMs: 86400000

websocket:
  allowedOrigins: "*"
  maxTextMessageSize: 8192
  maxBinaryMessageSize: 8192

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, websocket

logging:
  level:
    com.auction.notification: DEBUG
    org.springframework.web.socket: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/