server:
  port: 8086

spring:
  application:
    name: auction-query-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auction_query_db
    username: postgres
    password: Edgar123456/
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

auth:
  jwtSecret: "mi_super_clave_secreta_para_jwt_2025_con_al_menos_64_caracteres_para_HS512_seguridad_completa"
  jwtExpirationMs: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

sync:
  auctions:
    enabled: true
    interval: 300000 # 5 minutos