server:
  port: 0

# JWT Configuration
auth:
  jwtSecret: "mi_super_clave_secreta_para_jwt_2025_con_al_menos_64_caracteres_para_HS512_seguridad_completa"
  jwtExpirationMs: 86400000 # 24 hours in milliseconds

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:26262/users_db?user=root&password=
    username: root
    password:
#    url: jdbc:postgresql://localhost:5432/users_db
#    username: postgres
#    password: Edgar123456/
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.auction.user: DEBUG
    org.springframework.security: DEBUG

rabbitmq:
  queue:
    user: user.queue

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
